version: "3.8"
services:
  
  consul:
    image: docker.io/library/consul:1.4.0
    container_name: consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    volumes:
      - consul-data:/consul/data
    command: "agent -server -ui -node=consul -bootstrap-expect=1 -client=0.0.0.0"
    networks:
      - archlabs-network

volumes:
  consul-data:
    external: true

networks:
  archlabs-network:
    external: true