version: "3.8"
services:
  
  mysql:
    image: docker.io/library/mysql:8.0.31
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      # Default user is -> root
      MYSQL_ROOT_PASSWORD: 'SevenEightTwo782' # Change to your unique password
    networks:
      - archlabs-network

volumes:
  mysql-data:
    external: true

networks:
  archlabs-network:
    external: true