version: "3.8"
services:
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5671:5672'
      - '15671:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - my-network

volumes:
  rabbitmq-data:
    external: true
  rabbitmq-log:
    external: true

networks:
  my-network:
    external: true