version: "3.8"
services:
  
  redis:
    ports:
      - "6379:6379"
    image: redis:latest
    container_name: redis
    command:
      - redis-server
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru
    volumes:
      - 'redis-bitnami-data:/bitnami/redis/data'
      - 'redis-data:/data'
    networks:
      - my-network

networks:
  my-network:
    external: true

volumes:
  redis-bitnami-data:
    external: true
  redis-data:
    external: true