version: "3.8"
services:
  
  redis:
    ports:
      - "6379:6379"
    image: bitnami/redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: 'SevenEightTwo782'
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local