version: "3.8"
services:
  
  redis:
    ports:
      - "6379:6379"
    image: redis:latest
    container_name: redis
    command:
      - redis-server
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru
    networks:
      - redis-network
  
  rebrow:
    ports:
      - "5001:5001"
    image: marian/rebrow
    container_name: redis-browser
    links:
      - redis
    networks:
      - redis-network

networks:
  redis-network:
    external: false